### ISSUE TITLE
数据错误，缺少收盘价

### ISSUE THREAD

**Issue by zillionare** [zillionare/omega#54]
错误信息：
```
2022-06-21 11:21:19,230 E 353501 omicron.dal.influx.influxclient:query:236 | could not convert string to float: ''
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/omicron/dal/influx/influxclient.py", line 234, in query
    return deserializer(body)
  File "/root/miniconda3/lib/python3.8/site-packages/omicron/dal/influx/serialize.py", line 649, in __call__
    arr = np.loadtxt(
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1163, in loadtxt
    chunk.append(packer(convert_row(words)))
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1145, in convert_row
    return [conv(val) for conv, val in zip(converters, vals)]
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1145, in <listcomp>
    return [conv(val) for conv, val in zip(converters, vals)]
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 725, in _floatconv
    return float(x)  # The fastest path.
ValueError: could not convert string to float: ''
2022-06-21 11:21:19,235 W 353501 omicron.dal.influx.influxclient:query:237 | failed to deserialize data: b',result,table,_time,code,close,high_limit,low_limit\r\n,_result,0,2022-05-30T00:00:00Z,301043.XSHE,24.489999771118164,29.639999389648438,19.760000228881836\r\n,_result,0,2022-05-31T00:00:00Z,301043.XSHE,24.56999969482422,29.389999389648438,19.59000015258789\r\n,_result,0,2022-06-01T00:00:00Z,301043.XSHE,25.520000457763672,29.479999542236328,19.65999984741211\r\n,_result,0,2022-06-02T00:00:00Z,301043.XSHE,25.739999771118164,30.6200008392334,20.420000076293945\r\n,_result,0,2022-06-06T00:00:00Z,301043.XSHE,25.989999771118164,30.889999389648438,20.59000015258789\r\n,_result,0,2022-06-07T00:00:00Z,301043.XSHE,25.75,31.190000534057617,20.790000915527344\r\n,_result,0,2022-06-08T00:00:00Z,301043.XSHE,25.610000610351562,30.899999618530273,20.600000381469727\r\n,_result,0,2022-06-09T00:00:00Z,301043.XSHE,24.979999542236328,30.729999542236328,20.489999771118164\r\n,_result,0,2022-06-10T00:00:00Z,301043.XSHE,25.200000762939453,29.979999542236328,19.979999542236328\r\n,_result,0,2022-06-13T00:00:00Z,301043.XSHE,,30.239999771118164,20.15999984741211\r\n,_result,0,2022-06-14T00:00:00Z,301043.XSHE,25.280000686645508,30.600000381469727,20.399999618530273\r\n,_result,0,2022-06-15T00:00:00Z,301043.XSHE,24.950000762939453,30.239999771118164,20.15999984741211\r\n,_result,0,2022-06-16T00:00:00Z,301043.XSHE,25.18000030517578,29.940000534057617,19.959999084472656\r\n,_result,0,2022-06-17T00:00:00Z,301043.XSHE,25.059999465942383,30.219999313354492,20.139999389648438\r\n,_result,0,2022-06-20T00:00:00Z,301043.XSHE,25.549999237060547,30.06999969482422,20.049999237060547\r\n\r\n', the query is:from(bucket: "zillonare")
```
注意这里的\r\n,_result,0,2022-06-13T00:00:00Z,301043.XSHE,,30.239999771118164,20.15999984741211，缺少close信息。

```
await Stock.get_bars("301043.XSHE", 10, FrameType.DAY, end=datetime.date(2022, 6,15))
array([(datetime.date(2022, 6, 1), 24.811234, 25.907753, 24.801264, 25.43924 , 1408685.93516552, 35901510., 1.       ),
       (datetime.date(2022, 6, 2), 25.419304, 25.748259, 25.010601, 25.658543, 1029955.26711196, 26315239., 1.       ),
       (datetime.date(2022, 6, 6), 25.429272, 26.067245, 25.369461, 25.907753,  960052.18394399, 24976713., 1.       ),
       (datetime.date(2022, 6, 7), 26.117088, 26.117088, 25.150156, 25.668512,  648603.91876394, 16757404., 1.       ),
       (datetime.date(2022, 6, 8), 25.538923, 25.7981  , 24.980696, 25.528955,  737857.57092237, 18856921., 1.       ),
       (datetime.date(2022, 6, 9), 25.30965 , 25.399366, 24.691614, 24.900948,  589129.72766161, 14809941., 1.       ),
       (datetime.date(2022, 6, 10), 24.920885, 25.279747, 24.372627, 25.120253,  476786.37688756, 12027770., 1.       ),
       (datetime.date(2022, 6, 14), 25.140188, 25.299683, 24.522152, 25.2     ,  541680.36211729, 13610917., 1.       ),
       (datetime.date(2022, 6, 15), 25.15    , 25.53    , 24.92    , 24.95    ,  471294.        , 11903230., 1.0031747)],
      dtype=[('frame', 'O'), ('open', '<f4'), ('high', '<f4'), ('low', '<f4'), ('close', '<f4'), ('volume', '<f8'), ('amount', '<f8'), ('factor', '<f4')])
```

**Comment by zillionare** [comment]
301037.XSHE,缺少5月31日数据

**Comment by henrycs** [comment]
所有日线数据已修正
